name: DebugBuild
on:
  push:
    branches:
      - master
env:
  SOLUTION_FILE_PATH: UnoEngine.vcxproj
  CONFIGURATION: Debug
  VCPKG_DEFAULT_BINARY_CACHE: C:/vcpkg_cache
jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore ${{ env.SOLUTION_FILE_PATH }} -PackagesDirectory packages

      - name: Create vcpkg cache directory
        run: New-Item -ItemType Directory -Force -Path C:/vcpkg_cache

      - name: Cache vcpkg
        id: cache-vcpkg
        uses: actions/cache@v4
        with:
          path: C:/vcpkg/installed
          key: vcpkg-installed-v1

      - name: Install vcpkg dependencies
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        run: |
          C:\vcpkg\vcpkg install imgui[core,dx12-binding,win32-binding,docking-experimental]:x64-windows nlohmann-json:x64-windows assimp:x64-windows

      - name: Create CI.props
        run: |
          @"
          <?xml version="1.0" encoding="utf-8"?>
          <Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
            <ItemDefinitionGroup Condition="'`$(Configuration)|`$(Platform)'=='Debug|x64'">
              <ClCompile>
                <AdditionalIncludeDirectories>C:\vcpkg\installed\x64-windows\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
              </ClCompile>
              <Link>
                <AdditionalLibraryDirectories>C:\vcpkg\installed\x64-windows\debug\lib;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
                <AdditionalDependencies>imguid.lib;assimp-vc143-mtd.lib;zlibd.lib;%(AdditionalDependencies)</AdditionalDependencies>
              </Link>
            </ItemDefinitionGroup>
          </Project>
          "@ | Out-File -FilePath "CI.props" -Encoding UTF8

      - name: Build
        run: msbuild ${{ env.SOLUTION_FILE_PATH }} /p:Platform=x64 /p:Configuration=${{ env.CONFIGURATION }} /p:PlatformToolset=v143 /p:ForceImportBeforeCppTargets="${{ github.workspace }}\CI.props"
